name: Tests

on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm run build
      - run: chmod +x ./lib/cli.js
      - run: npm test
